import assert from 'node:assert/strict';
import { normalizeFeed, freshVehicles } from './vehicles.mjs';
const v = { trip: { routeId: '10' }, vehicle: { id: '401' }, timestamp: 990, position: { latitude: 42.65, longitude: -73.75, bearing: 90 } };
const feed = normalizeFeed({ header: { timestamp: 1000 }, entity: [{ id: 'a', vehicle: v }, { id: 'b', vehicle: { ...v, position: { latitude: 0, longitude: 0 } } }, { id: 'c', vehicle: { ...v, timestamp: undefined } }] });
assert.equal(feed.vehicles.length, 1);
assert.equal(feed.vehicles[0].routeId, '10');
assert.equal(feed.vehicles[0].id, '401');
assert.equal(freshVehicles(feed.vehicles, 1100).length, 1);
assert.equal(freshVehicles(feed.vehicles, 1111).length, 0);
assert.equal(freshVehicles(feed.vehicles, 900).length, 0);
assert.throws(() => normalizeFeed({ entity: [] }), /timestamp/);
console.log('Feed normalization and stale-report checks passed.');
