import assert from 'node:assert/strict';
import { updateMotion, positionAt, distanceAt, pointAt } from './motion.mjs';
const path = { points: [[42, -73, 0], [42.01, -73, 1113.2], [42.01, -72.99, 1940]], speed: 8 };
const report = (s, timestamp, extra = {}) => {
  const [lat, lng] = pointAt(path, s);
  return { id: 'bus', routeId: '1', tripId: 'trip', shapeId: 'shape', lat, lng, timestamp, speed: null, stopped: false, ...extra };
};
const first = updateMotion(null, report(100, 100), path, 100);
assert.ok(distanceAt(first, 105) > 139, 'Moves between reports');
const before = distanceAt(first, 115);
const faster = updateMotion(first, report(280, 115), path, 115);
assert.ok(Math.abs(distanceAt(faster, 115) - before) < .001, 'No jump at receipt');
assert.ok(faster.speed > first.speed, 'GPS recalibrates speed');
assert.ok(distanceAt(faster, 116) - before > faster.speed, 'Behind prediction speeds up to catch GPS');
const slower = updateMotion(first, report(160, 115), path, 115);
assert.ok(slower.speed < first.speed, 'GPS slows prediction');
assert.ok(distanceAt(slower, 116) - before < slower.speed, 'Ahead prediction slows to reconcile');
assert.equal(updateMotion(faster, report(290, 115), path, 120), faster, 'Duplicate report cannot reset prediction');
assert.equal(updateMotion(faster, report(200, 110), path, 120), faster, 'Older observations ignored');
const stopped = updateMotion(faster, report(300, 130, {stopped: true}), path, 130);
assert.equal(stopped.speed, 0);
assert.ok(Math.abs(distanceAt(stopped, 250) - 300) < .1, 'Converges to stopped bus');
assert.equal(distanceAt(first, 160), distanceAt(first, 200), 'Prediction stops after horizon');
const bend = updateMotion(null, report(1100, 100), path, 100);
const location = positionAt(bend, 110);
assert.equal(location[0], 42.01, 'Follows route corner rather than a straight heading');
assert.ok(location[1] > -73);
const reset = updateMotion(faster, report(0, 130, {tripId: 'new-trip'}), path, 130);
assert.equal(reset.correction, 0, 'Trip change resets old motion');
assert.equal(distanceAt(reset, 130), 0);
const detour = updateMotion(first, {...report(100, 115), lng: -73.1}, path, 115);
assert.equal(detour.path, null, 'Off-route GPS is not snapped onto an unrelated road');
assert.deepEqual(positionAt(detour, 120), [detour.report.lat, detour.report.lng]);
console.log('Motion checks passed: continuity, speed correction, turns, stops, stale/duplicate reports, trip resets and detours.');
